### ISSUE TITLE
Cannot access form "arrays" in web interface

### ISSUE THREAD

**Issue by rjframe** [vibe-d/vibe.d#1984]
Are web interface array parameters as in http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/post/20928 still intended to work?
```
import vibe.web.web;

class MyWebService {
    // available as POST /form
    void postForm(string[] tags)
    {
        render!("some_template.dt", tags);
    }
}
```

I can't get this to work with the web interface; reading the data from the server request works though.

index.dt:
```
doctype html
html
    head
        title Testing
    body
        form(method="POST", action="form")
            input(name="data", type="text")
            input(name="data", type="text")
            input(name="data", type="text")
            button(type="submit") Submit
```
form.dt:
```
doctype html
html
    head
        title Data
    body
        p Data: #{data}
```
app.d:
```
import vibe.vibe;

void main()
{
    auto r = new URLRouter;
    r.registerWebInterface(new MyWebService);

    auto settings = new HTTPServerSettings;
    settings.port = 8080;
    settings.bindAddresses = ["::1", "127.0.0.1"];
    listenHTTP(settings, r);

    logInfo("Please open http://127.0.0.1:8080/ in your browser.");
    runApplication();
}

class MyWebService {
    void index() {
        render!("index.dt");
    }
    void postForm(string[] data) {
        render!("form.dt", data);
    }
}
```
This outputs: "Data: []" for any input.
I've tried 0.8.1 on Windows and Linux, and 0.7.32 on Linux, with the same behavior.

**Comment by aberba** [comment]
Try input(name="data[]", ....) for all inputs with the same name to make them available as an array on server side. Lets see if that works

**Comment by aberba** [comment]
I think `data[]` will be more appropriate as similar approach works in PHP.

**Comment by schveiguy** [comment]
I want this to happen. Will try to make a PR.

The reason why this is important, is because on the client side, adding/removing extra items to be sent via jquery in a form is much more cumbersome if you have to rename the prototype elements.

For example, with my php application, I have something like (using diet here for brevity):

```pug
form(action="processData")
  .prototypeData
    input(type="text",name="title[]")
    input(type="number",name="value[]")
```
Now, in javascript, I can make copies of the prototype data over and over, and I don't have to change anything. I get 2 arrays as input, a `title` array and a `value` array. My JS code is super-simple.

Even when I output the form in diet, it can be much easier to print each item.

With vibe.d, I currently have to go through all the items and figure out how many there are, then append a number. Very annoying. And I also have to know what things to look for, if I don't want to write really complex JS code.

With this one server tweak, I can avoid all that.

**Comment by schveiguy** [comment]
Also note that reordering rows is trivial with this approach -- the client sends the items in the order they appear in the form. So all you need to do to change the order of a submitted array is to reorder the elements.

**Comment by schveiguy** [comment]
PR made, see note above.
