### ISSUE TITLE
The entire server slows down when function sendFile in fileserver is acessed

### ISSUE THREAD

**Issue by tony2038** [vibe-d/vibe.d#1986]
Here's my test code:
        auto router = new URLRouter;
        router.get("/", &index);
        router.get("/test", &test);
        router.get("/filetest", &fileTest);
        auto settings = new HTTPFileServerSettings;
        settings.serverPathPrefix = "/files";
        router.get("/files/*", serveStaticFiles("/var/www/files/", settings));
The entire server slows down when the content of fileserver is accessed

**Comment by s-ludwig** [comment]
If you are using the default libevent based diver on Linux, then file access is still implemented as standard non-asynchronous I/O calls, which would explain the behavior. The recommended way to avoid this is to use the new [vibe-core](https://github.com/vibe-d/vibe-core/) module, since that is about to become the new default anyway. But since there are a few breaking changes, another possibility with potentially less friction is to use the libasync based driver.

To use vibe-core, add this to dub.sdl:

    dependency "vibe-d:core" version="*"
    subConfiguration "vibe-d:core" "vibe-core"

or this to dub.json:

    "dependencies": {
        ...
        "vibe-d:core": "*"
    },
    "subConfigurations": {
        "vibe-d:core": "vibe-core"
    }

For libasync, just "vibe-core" with "libasync" in the sub configuration directive.

**Comment by tony2038** [comment]
Sorry, my english is very poor.
Thank you for your answer.
I have added the above configuration to dub.json, and the service hasn't become slow, the access same file use fileserver is  twice as fast as before, but it is a little slower than direct use readFile().
```
use fileserver：
Requests per second:    11252.88 [#/sec] (mean)
use readFile():
Requests per second:    14846.67 [#/sec] (mean)
```
test by ab on Linux.
