### ISSUE TITLE
shared static this() instead void main()

### ISSUE THREAD

**Issue by artemirq** [vibe-d/vibe.d#2034]
I get this errors if use `shared static this() {}` instead `void main() {}`

![image](https://user-images.githubusercontent.com/17342159/34909857-de595ac6-f8ba-11e7-9ed1-bbcd473ead1a.png)

**Comment by s-ludwig** [comment]
The `shared static this` vs. `main` behavior got reversed a while ago, so that `main` is the recommended default. To still use the `shared static this` approach, it is now necessary to define `"versions": ["VibeDefaultMain"]` in dub.json.

Note that most of the linker errors are just noise. The only interesting bit is the "no start address" at the end.

**Comment by artemirq** [comment]
@s-ludwig Thank you!
