### ISSUE TITLE
Special handling of `id` parameter for `registerRestInterface` should be documented

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe.d#2118]
Currently, there is scarce documentation on the legacy feature of `registerRestInterface` to incorporate a parameter named `id` into the route itself. The only thing I can find on the documentation is an example on http://vibed.org/api/vibe.web.rest/registerRestInterface.

But it is nowhere to be found here: http://vibed.org/api/vibe.web.rest/ where the whole mechanism is discussed in detail.

It should be documented formally, if nothing else to warn people what happens. See for instance this conversation: http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/50069/

Also note from Kai's book:

> If the first parameter of a method is named id, then this parameter is mapped to the void putData(string id, string data); path using the /:id/data path. This is really a legacy mechanism but you must be aware of it in order to avoid surprises.

**Comment by jblachly** [comment]
It appears the code that makes "id" special is here inside `RestInterface(TImpl).computeRoutes`:
https://github.com/vibe-d/vibe.d/blob/35079d4cf348e36785783480535ff186f2e4ef02/web/vibe/web/internal/rest/common.d#L184-L190

Because much of REST interface generator (intriguingly, not including the Collections interface?) was pulled into this internal module (`internal/rest/common.d`), these structs etc. do not appear in the automatically-generated documentation on https://vibed.org/ : https://vibed.org/api/vibe.web.rest/ -- (although this `id` behavior is still undocumented anyway).

Looking at the Collections Interface ( below ) it seems like the preferred method of having function parameters appear within the route is to prefix them with `_`:
https://github.com/vibe-d/vibe.d/blob/35079d4cf348e36785783480535ff186f2e4ef02/web/vibe/web/rest.d#L884-L892

**Comment by Geod24** [comment]
Fixed by #2464
