### ISSUE TITLE
Vibe.d 0.8.4 should be released as 2.080.0 isn't supported by 0.8.3

### ISSUE THREAD

**Issue by wilzbach** [vibe-d/vibe.d#2156]
e.g. https://github.com/vibe-d/vibe.d/issues/2155

Maybe it's time to switch to a `master` / `stable` cycle?
It's not too hard, it essentially means running the [`merge_stable`](https://github.com/wilzbach/git-tools/blob/master/merge_stable) script once in a while (i.e. when you want things from stable back in master).
I'm happy to volunteer to do the back-merging from stable as being able to quickly release a new patch (not alpha version) would greatly help with the project tester too.

**Comment by s-ludwig** [comment]
No, please no additional overhead in the development cycle, shouldn't the project tester avoid this situation anyway? BTW, I'm using vibe.d 0.8.3 together with DMD 2.080.0 just fine. #2155 also doesn't seem to be related to 2.080.0.

**Comment by wilzbach** [comment]
We currently have disabled vibe.d partially on the project tester due to regressions into which no one had time to look into :/

**Comment by wilzbach** [comment]
Also it looks like a 0.8.4 would fix the nightly build for run.dlang.io as it builds vibe.d with the latest nightly:

https://github.com/dlang-tour/core/issues/696
https://travis-ci.org/dlang-tour/core-exec/jobs/380245349

Well, imho being able to release hitfixs quickly is more than a reason enough to bother with two branches.
As mentioned I wouldn't mind taking care of the stable branch and merging hot fixes back into master.

**Comment by s-ludwig** [comment]
Hm, have those regressions been missed because the tests on the project tester were already disabled, or have they been ignored? The project tester used to work quite well for a while, but now it appears that it slowly loses its value.

But releasing quick hotfix releases is nothing that requires permanently maintaining two branches. Just creating a branch for the hopfefully rare case for which a hotfix release is needed is enough and has happened in the past.

Anyway, I'll tag a v0.8.4.rc.1 ASAP.

**Comment by wilzbach** [comment]
Well when we had this issue with the code.dlang.org being often down and the second mirror being out of date a lot of projects depending on vibe.d needed to be disabled and sadly a regression managed to get thru in this time which is why I couldn't simply enable vibe.d back once the registry issue had been fixed.
So the project tester would have prevented this.

Thanks a lot for tagging the RC!
