### ISSUE TITLE
HTTPServerResponse.redirect should use URL encoding

### ISSUE THREAD

**Issue by lionello** [vibe-d/vibe.d#2326]
Some web browser and/or HTTP proxies don't seem to handle UTF-8 encoded non-ASCII header values correctly. Tested on Azure, where the load-balancer re-encoded the headers and non-ASCII characters got corrupted. Fixed by using `res.redirect(urlEncode(url, ":/."));` instead.

Expected:
`res.redirect(url);` should work regardless of the characters in `url`. Redirecting to a URL with non-ASCII characters should result in a `Location:` HTTP header that uses URL encoding to represent any non-ASCII characters in the URL. Alternatively, `redirect` could `throw` on non-ASCII characters.

Actual:
`res.redirect(url);` results in an HTTP response with `Location:` header followed by the actual UTF-8 representation of `url`, causing corruption when handled by proxies/browser that don't expect UTF-8 encoded headers.

**Comment by s-ludwig** [comment]
Since URLs are not allowed to contain non-ASCII characters, I think the right way to go is to just validate that the passed string is well formed. The act of URL encoding can only be done correctly by the application in the general case anyway, and forcing it within the API would make it impossible to pre-encode the URL (e.g. when a path segment contains an encoded '%2F' vs. a literal '/' path separator).

**Comment by lionello** [comment]
That's a good point. So maybe there should be some header value validation to avoid responding with potentially incompatible values?

**Comment by lionello** [comment]
Closing as silently encoding is indeed a bad idea.
