### ISSUE TITLE
Remove SSLv3 support

### ISSUE THREAD

**Issue by kubo39** [vibe-d/vibe.d#2350]
- SSLv3 is susceptible to downgrade attacks a.k.a. POODLE 5 years ago.
- [rfc7568](https://tools.ietf.org/html/rfc7568) says SSLv3 MUST NOT be used.
- Mozilla called [the end of SSL 3.0](SSLv3 MUST NOT be used) in 2014.
- [couldflare: SSLv3 Support Disabled By Default](https://blog.cloudflare.com/sslv3-support-disabled-by-default-due-to-vulnerability/) in 2014.
-  [Google diabling SSLv3](https://security.googleblog.com/2015/09/disabling-sslv3-and-rc4.html) in 2014.

I'm not sure why SSLv3 is still supported by vibe.d, but it's time we remove it, as it's not just obsolete, but insecure.

**Comment by Geod24** [comment]
Vibe.d does not implement SSL directly, instead relying on either OpenSSL or Botan (with OpenSSL the default).
AFAICS SSLv3 was disabled because OpenSSL disabled it: https://github.com/vibe-d/vibe.d/pull/1316

The only thing left to do, AFAICS, is https://github.com/vibe-d/vibe.d/blob/03b85894ff8e88f3f92001c0750f809aa3ccb1f8/tls/vibe/stream/tls.d#L337

**Comment by kubo39** [comment]
If I'm correct, this PR only says that SSLv3* methods were removed from OpenSSL on debian.
Although vibe.d disabled SSLv3 by default, SSLv3 connections can still be achieved by passing the  SSL_OP_NO_SSLv3 options to OpenSSL.
