### ISSUE TITLE
Writing diet template to WebSocket

### ISSUE THREAD

**Issue by TimCoraxAudio** [vibe-d/vibe.d#2533]
I'm trying to compile a diet template outside of anything with an HTTPServerResponse so that I can send a generated HTML file to javascript in the browser to insert into the served pages HTML. Am I right in coming to the conclusion that this isn't possible? It seems as though the only way to compile a diet template is to a page request of some sort. Is there any way at all to send a piece of compiled template to javascript running in the browser?

**Comment by s-ludwig** [comment]
You can also use `diet-ng` directly (this is just being indirectly called by `render`) and write to any output range - in this case to an `appender!string`:
```D
import diet.html;
import std.array : appender;

auto result = appender!string;
result.compileHTMLDietFile!("mytemplate.diet", ...);
websocket.send(result.data);
```

**Comment by TimCoraxAudio** [comment]
Oh perfect. There was no way I was going to figure that out on my own.

Thanks for the heads up.

**Comment by s-ludwig** [comment]
I have improved the `compileHTMLDietFile` documentation a bit, to work around the fact that the function signature doesn't appear correctly: [35c7d9e](https://github.com/rejectedsoftware/diet-ng/commit/35c7d9e0321ed9b5198e542c49a6397bb295421e)

The [documentation for `render`](https://vibed.org/api/vibe.http.server/render) also links to `compileHTMLDietFile`, so that there is at least a chance that someone can find it.
