### ISSUE TITLE
URL cannot be constructed at build time

### ISSUE THREAD

**Issue by mkykadir** [vibe-d/vibe.d#2632]
Schema check causes compile time error when `URL` type is constructed at compile time

Example code (define as global);

```
public immutable URL[] samples = [
    URL("http://example.com"), URL("http://example.org"),
];
```

Compilation error:

```
url.d(730,25): Error: static variable `map_commonInternetSchemas` cannot be read at compile time
url.d(730,24):        called from here: `atomicLoad(map_commonInternetSchemas)`
```

**Comment by Geod24** [comment]
@s-ludwig : After a quick look, `URL.toString` and `URL.this(string, bool = true)` are not CTFE-able anymore.
IMO that's not a big deal, as the other overloads are, so values can be constructed at compile time. What do you think ?

**Comment by s-ludwig** [comment]
I'm leaning towards adding a way to construct with an explicit `this(string, Flag!"isCommonInternetSchema")` (or custom enum), storing the value in `URL`, so that `toString` also works at CTFE. Ultimately I'd like to switch to URL simply containing the string representation directly, reading/parsing individual parts on-demand, in which case `toString` would also trivially work.

(Regarding the `this(string, bool)` overload, I think we'll have to (re)move this before the next release and move the logic to a separate static/global function, or at least introduce a `URLParsingMode` enum instead of just `bool`.)
