### ISSUE TITLE
HTTPClient invalid memory operation error

### ISSUE THREAD

**Issue by etcimon** [vibe-d/vibe.d#895]
I was stuck on a problem in a big project and thought it could be documented better.

The function `HTTPClientResponse requestHTTP(string url, void delegate(HTTPClientRequest ...` is prone to errors, forgetting to use `response.dropBody()` will cause an output like this one and a random crash:

WARNING: HTTPClientResponse not fully processed before being finalized
Invalid Memory Operation

The GDB backtrace shows no specific information, but it happens within the GC collection. Other than the warning, there's no hope to track it back to the source, it's like finding a needle in a haystack.

The current implementation is prone to hard-to-debug errors, solution would be to return an initialized `HTTPClientResponseRef` object that wraps the pointer and has a `~this() { m_impl.dropBody(); }`.

**Comment by Geod24** [comment]
This was a bug in druntime, fixed in the latest release (v2.097.0).
`assert` used to allocate on failure, so any `assert` in a dtor would give you this `InvalidMemoryOperationError`.
There were a few related issues, e.g. https://github.com/vibe-d/vibe.d/issues/2178 and https://github.com/vibe-d/vibe.d/issues/1219
